name: Build and Run Tests

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  run-tests:
    name: 'Run tests'
    runs-on: ubuntu-22.04
    container: explyt/tsa-env:v1.1.0

    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4
        with:
          submodules: recursive

#        We don't need to setup Java because it is manually installed in the Docker image
#      - uses: actions/setup-java@v4
#        with:
#          distribution: 'temurin'
#          java-version: '17'
#          cache: 'gradle'

      - name: 'Build and run test'
        run: ./gradlew clean build
        env:
          TSA_RUN_HARD_TESTS: 1

      - name: 'Save test report'
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: ${{ github.workspace }}/**/build/reports/tests/
